django_rasa/core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('webhook', views.webhook, name='webhook'),
]

django_rasa/django_rasa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("aspu-admin/", admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("user.urls", namespace="user")),
    path("university/", include("university.urls", namespace="university")),
]

django_rasa/user/urls.py
from django.urls import path

from .views import UserLogin, UserLogout, profile

app_name="user"

urlpatterns = [
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),
    path('profile/', profile, name='profile'),
]

django_rasa/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# from university.models import Faculty

class User(AbstractUser):
    MALE, FEMALE = "m", "f"
    GENDER_OPTIONS = (
        (MALE, "Male"),
        (FEMALE, "Female"),
    )

    father_name = models.CharField("Father Name", max_length=50, null=True, blank=True)
    phone = models.CharField("Phone Number", max_length=15, null=True)
    gender = models.CharField(
        "Gender", choices=GENDER_OPTIONS, max_length=10, default=MALE
    )
    email = models.EmailField ("Email", null=False, blank=False)
    address = models.CharField("Address", max_length=100, null=True, blank=True)
    nationality = models.CharField("Nationality", max_length=100, null=True, blank=True)
    birth_date = models.DateField("Birth Date", null=True, blank=True)

    bank_name = models.CharField("Bank Name", null=True, blank=True, max_length=50)
    bank_card_num = models.CharField(
        "bank Card Number", null=True, blank=True, max_length=50
    )
    profile_image = models.ImageField(
        "Profile Image", upload_to="profile_images", null=True, blank=True,
    )

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"


class Student(models.Model):
    id = models.IntegerField("Student ID", primary_key=True)
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, related_name="student_user"
    )
    # faculty = models.ForeignKey(Faculty, verbose_name="Faculty", null=True, blank=False, on_delete=models.SET_NULL)
    
    def __str__(self) -> str:
        if self.user.first_name and self.user.last_name:
            return self.user.first_name + " " + self.user.last_name
        else:
            return str(self.user)

    class Meta:
        verbose_name = "Student"
        verbose_name_plural = "Students"


class Lecturer(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, related_name="lecturer_user"
    )

    certificate = models.CharField("Certificate", max_length=50, null=True, blank=True)
    certificate_date = models.DateField("Certificate Date", null=True, blank=True)
    
    def __str__(self) -> str:
        if self.user.first_name and self.user.last_name:
            return self.user.first_name + " " + self.user.last_name
        else:
            return str(self.user)

    class Meta:
        verbose_name = "Lecturer"
        verbose_name_plural = "Lecturers"

django_rasa/user/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from user.models import Student
from university.models import StudentDegree


class UserLogin(LoginView):
    template_name='user/login.html'
    next_page="/user/profile"
    
    
    
class UserLogout(LogoutView):
    template_name='user/logout.html'
    next_page="/"
    
    
@login_required(login_url='/user/login/')
def profile(request):
    template_name = "user/profile.html"
    student = Student.objects.get(user=request.user)
    
    ctx = {
        'degrees': StudentDegree.objects.filter(student=student)
    }
    
    return render(request, 'user/profile.html', ctx)
    


# class LoginView(InvalidFormMixin, BaseLoginView):
#     """
#     Login view
#     """
#     # http_method_names = ['post']
#     form_class = AuthenticationForm
#     template_name = 'account/login.html'
#     allow_authenticated = False

#     def get_form_kwargs(self):
#         kw = super(LoginView, self).get_form_kwargs()
#         kw.update({'request': self.request})
#         return kw

#     def form_valid(self, form):

#         login(self.request, form.get_user())
#         message = _("Welcome back, %s! Redirecting ...") % form.get_user().name
#         url = self.get_success_url()
#         if self.request.GET.get('amount') and self.request.GET.get('gateway'):
#             amount = self.request.GET.get('amount')
#             gateway = self.request.GET.get('gateway')
#             project = self.request.GET.get('project')
#             url = url + '?amount=' + amount + '&gateway=' + gateway + '&project=' + project
#         data = {
#             'message': message,
#             'redirect_url': url
#         }

#         if not form.cleaned_data.get('remember_me'):
#             self.request.session.set_expiry(0)

#         return JsonResponse(data, status=200)

django_rasa/templates/user/login.html
{% extends 'base.html' %}


{% block content %}


<!-- Courses -->
<div class="courses">
  <div class="container">
    <div class="row">

      <!-- Courses Main Content -->
      <div class="col-lg-12">
        <div class="courses_container">
          <div class="row courses_row">
            <h3>Student login</h3>
          </div>
          <div class="row courses_row">
            <div>
              <form method="post">
                {% csrf_token %}
                <div class="form-group">
                  <label class="control-label">Username</label>
                  {% if form.username.errors %}
                  <div class="form-error">{% endif %}
                    {{ form.username }}
                    {% if login_form.username.errors %}{{form.username.errors}}</div>{%endif %}
                </div>
                <div class="form-group">
                  <label class="control-label">Password</label>
                  {% if form.password.errors %}
                  <div class="form-error">{% endif %}
                    {{ form.password }}
                    {% if form.password.errors %}{{form.password.errors}}</div>{%endif %}
                </div>
                <div class="button-row justify-content-start m-0">
                  <button type="submit" class="btn btn-primary">Login</button>
                </div>
              </form>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

django_rasa/templates/user/logout.html
{% extends 'base.html' %}


{% block content %}


<!-- Courses -->
<div class="courses">
    <div class="container">
        <div class="row">

            <!-- Courses Main Content -->
            <div class="col-lg-12">
                <div class="courses_container">
                    <div class="row courses_row">

                        <h2> You've been logged out<h3>
                        

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

django_rasa/templates/user/profile.html
{% extends 'base.html' %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}styles/about.css">
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}styles/about_responsive.css">
{% endblock extra_css %}

{% block content %}

<div class="feature">
    <div class="feature_background" style="background-image:url({{STATIC_URL}}images/courses_background.jpg)"></div>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="section_title_container text-center">
                    <h2 class="section_title">Welcome</h2>
                    <h3 class="section_title">Profile</h3>
                </div>
            </div>
        </div>
        <div class="row feature_row">

            <!-- Feature Content -->
            <div class="col-lg-6 feature_col">
                <div class="feature_content">
                    <!-- Accordions -->
                    <div class="accordions">
                        <div class="elements_accordions">
                            <h4>Student Information</h4>
                            <div class="accordion_container">
                                <div class="accordion d-flex flex-row align-items-center active"><div>Username: {{user}}</div></div>
                                <div class="accordion d-flex flex-row align-items-center active"><div>First name: {{user.first_name}}</div></div>
                                <div class="accordion d-flex flex-row align-items-center active"><div>Father name: {{user.father_name}}</div></div>
                                <div class="accordion d-flex flex-row align-items-center active"><div>Last name: {{user.last_name}}</div></div>
                                <div class="accordion d-flex flex-row align-items-center active"><div>Phone: {{user.phone}}</div></div>
                                <div class="accordion d-flex flex-row align-items-center active"><div>Gender: {{user.gender}}</div></div>
                                <div class="accordion d-flex flex-row align-items-center active"><div>Address: {{user.address}}</div></div>
                                <div class="accordion d-flex flex-row align-items-center active"><div>Nationality: {{user.nationality}}</div></div>
                                <div class="accordion d-flex flex-row align-items-center active"><div>Birth Date: {{user.birth_date}}</div></div>
                            </div>
                            <h4>Bank Info</h4>
                            <div class="accordion_container">
                                <div class="accordion d-flex flex-row align-items-center active"><div>Bank: {{user.bank_name}}</div></div>
                                <div class="accordion d-flex flex-row align-items-center active"><div>Bank Card: {{user.bank_card_num}}</div></div>
                            </div>
                        </div>
                    </div>
                    <!-- Accordions End -->
                </div>
            </div>

             <!-- Feature Content -->
             <div class="col-lg-6 feature_col">
                <div class="feature_content">
                    <!-- Accordions -->
                    <div class="accordions">
                        
                        <div class="elements_accordions">
                            <h4>Courses and Degrees</h4>
                            <div class="accordion_container">
                                {% for degree in degrees %}
                                <div class="accordion d-flex flex-row align-items-center active">
                                    {{degree.course}}: {{degree.degree}}
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <!-- Accordions End -->
                </div>
            </div>

            {% comment %} <!-- Feature Video -->
            <div class="col-lg-6 feature_col">
                <div class="feature_video d-flex flex-column align-items-center justify-content-center">
                    <div class="feature_video_background" style="background-image:url({{user.profile_image.url}}"></div>
                </div>
            </div> {% endcomment %}
        </div>

        <div class="button-row " style="margin-top: 5rem;">
            <div class="btn btn-primary"><a style="color: white;" href="{% url 'user:logout' %}">Logout</a></div>
        </div>
    </div>
</div>


{% endblock content %}